config/routes.rb
Rails.application.routes.draw do
 


 resources :posts do
  collection do 
    post :json_to_post
    get :inc_rating
  end
end




 root "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :tags, dependent: :destroy
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all
	end

	def new 
	end

	def create 
		@post = Post.new(post_params)

		@post.save

		redirect_to @post
	end

	def show 
		@post = Post.find(params[:id])
	end

	require 'open-uri'

	def json_to_post
		newPost = JSON.parse(params[:code])

		@post = Post.new
		@post.number = newPost['number']
		@post.body = newPost['body']
		@post.rating = newPost['rating']

		@post.save

		redirect_to root_path
	end

	def inc_rating
		@post = Post.find(params[:id])

		@post.rating = @post.rating + 1

		@post.save		

		render json: {rating: @post.rating}
	end

	private

	def post_params
		params.require(:post).permit(:number, :body, :rating)
	end

	
	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KMPClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1> This is index </h1>

<% @posts.each do |post|  %>
<%= post.number %>
<br>
<%= post.body %> 
<br>
Рейтинг: <div id="rating<%= post.id %>"><%= post.rating %> </div>
<br>
<button type="button" onclick="incratingajax(<%= post.id %>)">Любо!</button>
<br>
<% end %>



<br>

<%= link_to 'Новая статья', :action => 'new' %><br />

app/views/posts/new.html.erb
<h1> New Post </h1>

<%= form_for :post, url: posts_path do |f| %>
	<%= f.label :number %> <br>
	<%= f.text_field :number %> <br>
	<br>
	<%= f.label :body %><br>
	<%= f.text_field :body %><br>
	<br>
	<%= f.submit %>
<% end %>

<br>

<%= form_tag json_to_post_posts_path do %>
<%= text_area_tag :code %>
<%= submit_tag 'Отправить' %>
<% end %>

app/views/posts/show.html.erb
<h1> 
	<%= @post.number %>
</h1>

<p>
	<%= @post.body %>
</p> 

<%= link_to 'На главную', :action => 'index' %> 